name: Build Chocolate Doom (Windows ARM64/AArch64)

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-winarm64:
    runs-on: windows-11-arm
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: >-
            mingw-w64-clang-aarch64-clang
            mingw-w64-clang-aarch64-cmake
            mingw-w64-clang-aarch64-fluidsynth
            mingw-w64-clang-aarch64-libpng
            mingw-w64-clang-aarch64-libsamplerate
            mingw-w64-clang-aarch64-llvm-openmp
            mingw-w64-clang-aarch64-ninja
            mingw-w64-clang-aarch64-python-pillow
            mingw-w64-clang-aarch64-python3-yaml
            mingw-w64-clang-aarch64-SDL2
            mingw-w64-clang-aarch64-SDL2_mixer
            mingw-w64-clang-aarch64-SDL2_net
      - name: Build
        shell: msys2 {0}
        run: |
          cmake -B build -S .
          cd build
          ninja
          mkdir upload_doom
          cp src/chocolate-doom.exe upload_doom
          cp src/chocolate-setup.exe upload_doom/chocolate-doom-setup.exe
          strip upload_doom/*.exe
          mkdir upload_heretic
          cp src/chocolate-heretic.exe upload_heretic
          cp src/chocolate-setup.exe upload_heretic/chocolate-heretic-setup.exe
          strip upload_heretic/*.exe
          mkdir upload_hexen
          cp src/chocolate-hexen.exe upload_hexen
          cp src/chocolate-setup.exe upload_hexen/chocolate-hexen-setup.exe
          strip upload_hexen/*.exe
          mkdir upload_strife
          cp src/chocolate-setup.exe upload_strife/chocolate-strife-setup.exe
          cp src/chocolate-strife.exe upload_strife
          strip upload_strife/*.exe
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libc++.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libFLAC.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libfluidsynth-3.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libglib-2.0-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libgmodule-2.0-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libiconv-2.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libintl-8.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libmp3lame-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libmpg123-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libogg-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libomp.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libopus-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libopusfile-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libpcre2-8-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libpng16-16.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libportaudio.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libreadline8.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libsamplerate-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libsndfile-1.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libtermcap-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libvorbis-0.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libvorbisenc-2.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libvorbisfile-3.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libwavpack-1.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libwinpthread-1.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/libxmp.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/SDL2.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/SDL2_mixer.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/SDL2_net.dll {} \;
          find upload_doom upload_heretic upload_hexen upload_strife -type d -exec cp /clangarm64/bin/zlib1.dll {} \;
      - name: Upload as artifact (Chocolate Doom)
        uses: actions/upload-artifact@v4
        with:
          name: chocolate-doom-git-winarm64-${{github.sha}}
          path: build/upload_doom
          if-no-files-found: error
      - name: Upload as artifact (Chocolate Heretic)
        uses: actions/upload-artifact@v4
        with:
          name: chocolate-heretic-git-winarm64-${{github.sha}}
          path: build/upload_heretic
          if-no-files-found: error
      - name: Upload as artifact (Chocolate Hexen)
        uses: actions/upload-artifact@v4
        with:
          name: chocolate-hexen-git-winarm64-${{github.sha}}
          path: build/upload_hexen
          if-no-files-found: error
      - name: Upload as artifact (Chocolate Strife)
        uses: actions/upload-artifact@v4
        with:
          name: chocolate-strife-git-winarm64-${{github.sha}}
          path: build/upload_strife
          if-no-files-found: error
